### ISSUE TITLE
API Gateway timeout after 30 seconds 

### ISSUE THREAD

**Issue by mpizosdim** [philschmid/serverless-bert-with-huggingface-aws-lambda#3]
Nice repository and blogpost.

I tried to use it but I have a time out every time I call it. Which is due to the restrict max of 30 seconds on API Gateway.

I was wondering how did u handled that? Thanks

**Comment by philschmid** [comment]
Hey, 

I did not bypass the timeout. If you get the request you can send it like 1-2 seconds afterwards again and then it should work. 
This is sadly still a big problem. But I also created a new solution, where I mount an Amazon EFS into the lambda this is fast, but still runs sometimes at the first request in a timeout. 

https://www.philschmid.de/new-serverless-bert-with-huggingface-aws-lambda

**Comment by mpizosdim** [comment]
Thanks @philschmid . The trick with a 'dummy' initial call works but a bit risky. 

Great context also on your other blogpost! 
keep up the great work that you are sharing. Thanks again.
