### ISSUE TITLE
torch load issue (no GPU)

### ISSUE THREAD

**Issue by theashworld** [philschmid/serverless-bert-with-huggingface-aws-lambda#4]
Getting this error. 
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
I'll try with this option and update

**Comment by philschmid** [comment]
Hi theashworld,

currently, AWS Lambda doesn´t support GPU. So you cannot "enable" GPU in Pytorch.

**Comment by philschmid** [comment]
And i saw you are using an very old tutorial of how to use BERT in AWS Lambda. I wrote a new one, where we use docker as runtime for AWS. I think this is easier to implement

github: https://github.com/philschmid/serverless-bert-huggingface-aws-lambda-docker
blog: https://www.philschmid.de/serverless-bert-with-huggingface-aws-lambda-docker
